version: 2
jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Create server remote
          command: |
            git remote add server codegozq@codegeeks.in:/home3/codegozq/repos/AboutMe
      - run:
          name: Deploy to Codegeeks Server
          command: |
            git push server master

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
